version: '2'
services:
    backend:
        depends_on:
            - db
        environment:
            - APP_ENV=local
            - APP_MODE=development
            - API_DEBUG=true
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=paydek
            - DB_USERNAME=paydek
            - DB_PASSWORD=1234567890
        volumes:
            - ./app:/app

    db:
        image: "mariadb:10.4"
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            #- MYSQL_ROOT_PASSWORD=root
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_ONETIME_PASSWORD=yes
            - MYSQL_DATABASE=paydek
            - MYSQL_USER=paydek
            - MYSQL_PASSWORD=1234567890
            
    pma:
        image: phpmyadmin/phpmyadmin:4.6.3-3
        ports:
            - "8081:80"
        links:
            - db:db
        depends_on:
            - db
        environment:
            - PMA_USER=paydek
            - PMA_PASSWORD=1234567890

volumes:
    mysql-data: